### ISSUE TITLE
ARMv6 support disappeared

### ISSUE THREAD

**Issue by mthmulders** [jodersky/akka-serial#43]
I'm trying to upgrade my app (currently on flow 2.4.1) to the latest version of akka-serial.

I noticed that [native/lib_native/](https://github.com/jodersky/akka-serial/tree/master/native/lib_native) doesn't contain a folder called `armv6l-linux`, so I first built the [terminal sample](https://github.com/jodersky/akka-serial/tree/master/samples/terminal/src/main/scala/akka/serial/samples/terminal) and tried to run it:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Native library libakkaserial1.so (/native/armv6l-linux/libakkaserial1.so) cannot be found on the classpath.
	at akka.serial.sync.UnsafeSerial$.loadPackaged$1(UnsafeSerial.scala:20)
	at akka.serial.sync.UnsafeSerial$.load$1(UnsafeSerial.scala:20)
	at akka.serial.sync.UnsafeSerial$.<init>(UnsafeSerial.scala:20)
	at akka.serial.sync.UnsafeSerial$.<clinit>(UnsafeSerial.scala)
	at akka.serial.Serial$.debug(Serial.scala:136)
```

I've built a binary for armv6l-linux, put it in `src/main/resources/native` and re-packaged the sample. Now it outputs:

```
[INFO] [09/10/2017 12:58:36.848] [akka-serial-akka.actor.default-dispatcher-2] [akka://akka-serial/user/terminal] Requesting manager to open port: /dev/ttyUSB0, baud: 115200
Error acquiring lock on port: 11
[ERROR] [09/10/2017 12:58:37.288] [akka-serial-akka.actor.default-dispatcher-3] [akka://akka-serial/user/terminal] Connection failed, stopping terminal. Reason: akka.serial.PortInUseException: 
```
Which is expected since another process is using the port at the same time.

I think it would be nice to have armv6 support (see also #21). There is a work-around (by packaging the .so with my app) but it's not very elegant IMHO.

I can contribute the .so for armv6 either by e-mail (as I did for #21) or as a pull request. What would be your preferred method?

**Comment by jodersky** [comment]
I'd appreciate that! It would be great if you can attach the binary to this issue, or, even better, a PR with the binary added to the native_lib folder :)
The reason for it getting dropped is that IIRC there was an incompatible change in the native code that needed recompilation for all platforms. Since I currently do not have an armv6 device, it unfortunately was dropped.

**Comment by mthmulders** [comment]
Sure, not a single problem. In case you find yourself in the situation again where you need a change in the native code, feel free to contact me. I'd be happy to contribute by re-compiling the native code so we can keep armv6 support continued.

Disclaimer: as long as my Raspberry doesn't die :)
